### ISSUE TITLE
Control inputs partially not working

### ISSUE THREAD

**Issue by fiermanb** [MiSTer-devel/Arcade-Atari-system1_MiSTer#1]
For Road Runner (and possibly others too), inputs Up and Down are not registering in-game. Rebinding does not make any difference.

**Comment by d18c7db** [comment]
I can't help you much with such little info. What input? Are you using a keyboard? A joystick?
I tested with a 8BitDo USB connected joystik and all works well with the published core.
My guess is you need to go into sys menu and do something with the input mapping up to and including resetting it back to defaults. I'm fairly sure this isn't a game core issue.

**Comment by fiermanb** [comment]
Like I said, there really is nothing wrong with the physical controllers or the MiSTer setup at all. The fact that rebinding is possible in the game menu proves that. As I stated in my first post.

**Comment by d18c7db** [comment]
I'm trying to help you out here as best as I can or I can also take the stance that "my controller and other's works fine in this core" and leave you to it.

You are aware that it is possible to have custom binding of your controller _per_game_ so the fact your controller works everywhere else means nothing with respect to the problem you experience in this particular core.

If you look in the MiSTer folder /media/fat/config/inputs check if there are any files called roadrunn*_input*.map and if so then delete those bastards, reboot MiSTer and try again.

**Comment by fiermanb** [comment]
As I stated in the first post, I did try to rebind the controls for the game. Of course we are talking the Core/game specific rebinds here. (Define roadrunn buttons) The rebind dialogue works fine with the joystick, as in: up and down are mapped as valid input. - which means that the MiSTer framework is running as expected.

In game however, Up and Down are not registering. I would like to point out that I am not the only person with this issue. We can safely rule out user error here. (and yes, I did manually delete the input mapping files prior)

md5: a55212ebcb3a12cd7e91129ce3b08f22  atarisys1_20231130.rbf

**Comment by d18c7db** [comment]
I think there is a test you can do that will definitively show where the problem is, if you are willing to spend 10 minutes.

Backup and then delete all mappings in /media/fat/config/inputs so the folder is empty
Reboot MiSTer
Run the Utility "InputTest"
Press and hold Select until the menu pops up and select "Analog"
Ensure that "PAD 1" is shown at the top between "ANALOG LEFT" and "ANALOG RIGHT" else select PAD1 with A/B keys
Mush around all the controls on your controller and figure out which ones move the ANALOG LEFT cross up down left right

After having done the above _without any key remapping in place_ run the problematic core and use the _same keys_ that moved the cross up/down/left/right and see if they work inside the core.

**Comment by fiermanb** [comment]
Ran through everything, and the result is the same.
And yes, the analogue stick of any controller works fine. D-pad does not however. Digital inputs seem to be broken on the core end. Really - this is not a user-error case here.

**Comment by d18c7db** [comment]
Road Runners only responds to analog joystick by design. User is mixing analog controls for left/right with digital controls for up/down. This has nothing to do with remapping controls. Will implement digital controls in a future release.
